routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Ruta tipo resource que trae todo el CRUD, muestra todo
Route::resource('admin/categories', 'CategoryController')->names('categories');
//ruta de module
Route::get('admin/category/{module}', 'CategoryController@module')->name('categories.module');
//ruta subcategorias
Route::resource('admin/subcategories', 'SubcategoryController')->names('subcategories');
//ruta tags
Route::resource('admin/tags', 'TagController')->names('tags');
//ruta posts
Route::resource('admin/posts', 'PostController')->names('posts');


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use Softdeletes; //muestra la fecha de cuando es eliminado
    protected $fillable = [
        'user_id', 'category_id', 'name', 'slug', 'abstract', 'body', 'status',
    ];
    protected $dates=['deleted_at'];
    protected $hidden=['created_at', 'updated_at'];

    //relacion 1:1 de image y post
    public function image()
    {
        return $this->morphOne('App\Image', 'imageable');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class PostController extends Controller
{
    //middleware para que pida la autenticacion
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index() //lista todas las post registrados
    {
        $posts= Post::orderBy('id', 'DESC')->paginate(15);
        return view('admin.posts.index', compact('posts'));
    }


    public function create()
    {
        $categories=Category::orderBy('name', 'ASC')->pluck('name', 'id');//a q categoria pertence el post
        return view('admin.posts.create', compact('categories'));
    }


    public function store(Request $request)
    {
        //validacion
        $request->validate([
            'name'=> 'required|unique:posts|max:60',
            'user_id'=> 'required|integer',
            'category_id'=> 'required|integer',
            'abstract'=> 'required|max:500',
            'body'=> 'required',
            'status'=> 'required',
            'image'=>'image|dimensions:min_width=1200,max_width=1200,
            min_height=490, max_height=490|mimes:jpeg,jpg,png',//validacion de imagenes

        ]);

        //guardar la imagen validacion el el request if
        if ($request->hasFile('image')){
            $image= $request->file('image');
            $nombre= time().$image->getClientOriginalName();//se  captura la hora, se concatena con el nombre original del formulario
            $ruta=public_path().'/images'; //ruta donde se guardan las imagenes
            $image->move($ruta,$nombre);//se obtiene la imagen guardada en esta carpeta
            $urlimage['url']='/images/'.$nombre;//almacenar la imagen, el url y nombre. se concatena el url y el nombre

        }

        //slug automatico, la (e) es para que guarde en la BD
        $post=new Post;
        $post->user_id=e($request->user_id);
        $post->category_id=e($request->category_id);
        $post->name=e($request->name);
        $post->slug=Str::slug($request->name);
        $post->abstract=e($request->abstract);
        $post->body=e($request->body);
        $post->status=e($request->status);

        //guardar informacion
        $post->save();
        $post->image()->create($urlimage);//se vincule la imagen con el post creado
        return redirect()->route('posts.index')->with('info', 'Agregado correctamente');
    }

    //function module para listar el modulo
    public function module($module)
    {
        $posts=Post::where('module', $module)->orderBy('id', 'DESC')->paginate(15);
        return view('admin.posts.index', compact('posts'));


    }


    public function show(Post $post)
    {

    }


    public function edit($id)
    {
        //editar una post
        $post=Post::where('id', $id)->firstOrFail();
        $categories=Category::orderBy('name', 'ASC')->pluck('name', 'id');
        return view('admin.posts.edit', compact('post', 'categories'));
    }


    public function update(Request $request, $id)
    {
        //se validan los datos
        $request->validate([
            'name'=>'required|max:60',
            'user_id'=>'required|integer',
            'category_id'=>'required|integer',
            'abstract'=>'required|max:500',
            'body'=>'required',
            'status'=>'required',
            'image'=>'image|dimensions:min_width=1200, max_width=1200,min_height=490,
             max_height=490|mimes:jpeg,jpg,png',//validacion de imagenes

        ]);

        //guardar la imagen validacion el el request if

        if($request->hasFile('image')){
            $image=$request->file('image');
            $nombre = time().$image->getClientOriginalName();//se  captura la hora, se concatena con el nombre original del formulario
            $ruta = public_path().'/images'; //ruta donde se guardan las imagenes
            $image->move($ruta,$nombre);//se obtiene la imagen guardada en esta carpeta
            $urlimage['url']='/images/'.$nombre;//almacenar la imagen, el url y nombre. se concatena el url y el nombre

        }

        //se actualiza con el $id
        $post = Post::findOrFail($id);
        $post->user_id = e($request->user_id);
        $post->category_id = e($request->category_id);
        $post->name = e($request->name);
        $post->slug = Str::slug($request->name);
        $post->abstract = e($request->abstract);
        $post->body = e($request->body);
        $post->status = e($request->status);

        if ($request->hasFile('image')){
            $post->image()->delete();

         //se guarda y retorna a la vista
        }
        $post->save();
        if ($request->hasFile('image')){
            $post->image()->create($urlimage);//se vincule la imagen con el post creado
        }
        return redirect()->route('posts.index')->with('info', 'Actualizado correctamente');

    }


    public function destroy($id)
    {
        //alimina la categoria
        $post=Post::findOrFail($id)->delete();
        //retorna a la vista anterior
        return back()->with('info', 'Eliminado con éxito');

    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')
@section('title','Crear publicación')
@section('breadcrumb')
<li class="breadcrumb-item active">
	<a href="{{route('posts.index')}}">Publicaciones</a>
</li>
<li class="breadcrumb-item active">@yield('title')</li>
@endsection
@section('content')
<div class="card">
	<div class="card-header">
	  <h3 class="card-title">Registro de publicación</h3>
    </div>
    {!! Form::open(['route'=>'posts.store', 'method'=>'POST','files' => true]) !!}
	<div class="card-body ">
        @include('admin.posts.form.form')
	</div>
	<div class="card-footer">
      <a class="btn btn-danger float-right" href="{{route('posts.index')}}">Cancelar</a>
      <input type="submit" value="Guardar" class="btn btn-primary">
    </div>
    {!! Form::close() !!}
  </div>
@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')
@section('title','Editar publicación')
@section('breadcrumb')
<li class="breadcrumb-item active">
	<a href="{{route('posts.index')}}">Publicaciones</a>
</li>
<li class="breadcrumb-item active">@yield('title')</li>
@endsection
@section('content')
<div class="card">
	<div class="card-header">
	  <h3 class="card-title">Edición de publicación</h3>
    </div>
    {!! Form::model($post, ['route'=>['posts.update',$post->id],'method'=>'PUT','files' => true]) !!}
	<div class="card-body ">
    @include('admin.posts.form.form')
    <div class="card bg-dark text-white">
      <img class="card-img" src="{{$post->image->url}}" alt="Card image">
      <div class="card-img-overlay">
        <h5 class="card-title">Imagen de publicación</h5>
      </div>
    </div>
	</div>
	<div class="card-footer">
      <a class="btn btn-danger float-right" href="{{route('posts.index')}}">Cancelar</a>
      <input type="submit" value="Actualizar" class="btn btn-primary">
    </div>
    {!! Form::close() !!}
  </div>
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')
@section('title','Gestión de publicaciones')
@section('breadcrumb')
<li class="breadcrumb-item active">@yield('title')</li>
@endsection
@section('content')
<div class="card">
	<div class="card-header">
	  <h3 class="card-title">Sección de publicaciones</h3>
	  <div class="card-tools">
		<a type="button" class="btn btn-tool" href="{{route('posts.create')}}">
            <h3 class="card-title" >Agregar <i class="fas fa-plus"></i></h3>
        </a>
	  </div>
	</div>
	<div class="card-body table-responsive p-0">
		<table class="table table-head-fixed">
		  <thead>
			  <tr>
				  <th scope="col">ID</th>
				  <th>Nombre</th>
				  <th>Resumen</th>
				  <th colspan="3">&nbsp;</th>
			  </tr>
		  </thead>
		  <tbody>
			  @foreach ($posts as $post)
				<tr>
					<th scope="row">{{$post->id}}</td>
					<td>{{$post->name}}</td>
					<td>{{$post->abstract}}</td>
					<td width="10px">
						<a class="btn btn-warning" href="{{route('posts.show', $post->id)}}">
							<i class="fas fa-eye"></i>
						</a>
					</td>
					<td width="10px">
						<a class="btn btn-info" href="{{route('posts.edit', $post->id)}}">
							<i class="fas fa-edit"></i>
						</a>
					</td>
					<td width="10px">
						{!! Form::open(['route'=>['posts.destroy',$post->id], 'method'=>'DELETE']) !!}
						<button class="btn btn-danger">
							<i class="fas fa-trash-alt"></i>
						</button>
						{!! Form::close() !!}
					</td>
				</tr>
			  @endforeach	 
		  </tbody>
		</table>
	{{$posts->render()}}
	</div>
	<div class="card-footer">
	  Footer
	</div>
  </div>
@endsection

resources/views/admin/posts/show.blade.php
@extends('layouts.admin')
@section('title','Detalles publicación')
@section('breadcrumb')
<li class="breadcrumb-item active">
	<a href="{{route('posts.index')}}">Publicaciones</a>
</li>
<li class="breadcrumb-item active">@yield('title')</li>
@endsection
@section('content')
<div class="card">
	<div class="card-header">
	  <h3 class="card-title">Detalle de publicación</h3>
    </div>
	<div class="card-body ">
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mt-4">{{$post->name}}</h1>
              <p class="lead">
                Redactado por
                <strong >{{$post->user->name}}</strong>
              </p>
              <hr>
              <p>Publicado el {{$post->updated_at->format('d/m/y')}}</p>
              <hr>
              <img class="img-fluid rounded" src="{{$post->image->url}}" alt="">
              <hr>
              <p class="lead">{{$post->abstract}}</p>
              <p>
                {!!htmlspecialchars_decode($post->body)!!}
              </p>
              <hr>
            </div>
            <div class="col-md-4">
              <div class="card my-4">
                <h5 class="card-header">Categoría</h5>
                <div class="card-body">
                  <div class="row">
                    <div class="col-lg-6">
                      <ul class="list-unstyled mb-0">
                        <li>
                            {{$post->category->name}}
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
	</div>
	<div class="card-footer">
      <a class="btn btn-primary" href="{{route('posts.index')}}">Regresar</a>
    </div>
  </div>
@endsection